export const AUTH_USER = 'AUTH_USER';

export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const LOGOUT = 'LOGOUT'

export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const GET_MOVIES = 'GET_MOVIES';
export const SET_MOVIES = 'SET_MOVIES';

export const SET_PAGES = 'SET_PAGES';

export const GET_MOVIE = 'GET_MOVIE';
export const SET_MOVIE = 'SET_MOVIE';

export const ADD_NEW_MOVIE = 'ADD_NEW_MOVIE';
export const SET_NEW_MOVIE = 'SET_NEW_MOVIE';

export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const SET_QUERY = 'SET_QUERY';
export const SET_GENRE = 'SET_GENRE';

export const LIKE_MOVIE = 'LIKE_MOVIE';
export const SET_LIKED = 'SET_LIKED';
export const DISLIKE_MOVIE = 'DISLIKE_MOVIE';

export const REMOVE_LIKE = 'REMOVE_LIKE';
export const REMOVE_DISLIKE = 'REMOVE_DISLIKE';

export const GET_GENRES = 'GET_GENRES';
export const SET_GENRES = 'SET_GENRES';

export const ADD_MOVIE_ERROR = 'ADD_MOVIE_ERROR';

export const SET_OPEN = 'SET_OPEN';
export const SET_CLOSED = 'SET_CLOSED';

export const ADD_COMMENT = 'ADD_COMMENT';
export const SET_COMMENT = 'SET_COMMENT';

export const GET_WATCHLIST = 'GET_WATCHLIST';
export const SET_WATCHLIST = 'SET_WATCHLIST';

export const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST';
export const SET_TO_WATCHLIST = 'SET_TO_WATCHLIST';

export const REMOVE_FROM_WATCHLIST = 'REMOVE_FROM_WATCHLIST';
export const UNSET_FROM_WATCHLIST = 'UNSET_FROM_WATCHLIST';

export const MARK_AS_WATCHED = 'MARK_AS_WATCHED';
export const SET_AS_WATCHED = 'SET_AS_WATCHED';

export const GET_MOST_POPULAR = 'GET_MOST_POPULAR';
export const SET_MOST_POPULAR = 'SET_MOST_POPULAR';

export const GET_COMMENTS = 'GET_COMMENTS';
export const SET_COMMENTS = 'SET_COMMENTS';
export const SET_COMMENTS_ACTIVE_PAGE = 'SET_COMMENTS_ACTIVE_PAGE';
export const SET_COMMENTS_FIRST_PAGE_FETCHED = 'SET_COMMENTS_FIRST_PAGE_FETCHED';
export const SET_MORE_COMMENTS = 'SET_MORE_COMMENTS';

export const GET_RELATED = 'GET_RELATED';
export const SET_RELATED = 'SET_RELATED';

export const SET_LOADING = 'SET_LOADING';

export const SET_OMDB_OPEN = 'SET_OMDB_OPEN';

export const GET_MOVIE_FROM_API = 'GET_MOVIE_FROM_API';
export const SET_MOVIE_NOT_FOUND = 'SET_MOVIE_NOT_FOUND';
export const SET_OMDB_ACTIVE_MOVIE = 'SET_OMDB_ACTIVE_MOVIE';

export const SET_OMDB_CONFIRM_OPEN = 'SET_OMDB_CONFIRM_OPEN';

export const ADD_MOVIE_FROM_OMDB = 'ADD_MOVIE_FROM_OMDB';